dist: precise

language: php

before_script:
  - phpenv config-rm xdebug.ini

matrix:
  include:
  - php: "7.2"
  - php: "7.1"
  - php: "7.0"
  - php: "5.6"
  - php: "5.4"
  - php: "5.3"
script:
  - composer install
  - vendor/bin/phpunit