version: 2
jobs:
  build:
    docker:
      - image: splitbrain/phpfarm
    steps:
      - checkout
      - run: curl -s https://getcomposer.org/installer | php
      - run: composer.phar install
      - run: ./vendor/bin/phpunit
